# =============================================================================
# Interfascia - Frontend Minimalista
# =============================================================================

# Imagen base liviana de Python
FROM python:3.12-alpine

# Directorio de trabajo
WORKDIR /app

# Copiamos el frontend
COPY index.html .

# Exponemos el puerto del servidor HTTP
EXPOSE 3000

# Servimos el index.html mediante el servidor HTTP de Python
CMD ["python", "-m", "http.server", "3000"]